# Generated by Django 3.2.7 on 2021-09-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0002_auto_20210926_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
