# Generated by Django 3.2.7 on 2021-09-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0004_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
